/**
 * Every string of the phone program editor (editor spec, Part N), in one
 * place. Tests read them from here, so a wording change never needs a test
 * edit.
 */
export const editorUi = {
	createTitle: 'Create program',
	editTitle: 'Edit program as new version',
	cancel: '← Cancel without saving',
	createNote: 'Pick a starting point, edit, review, then save. Nothing is saved until you save.',
	editNote:
		'Saving creates a new version and archives this source program. Past workouts stay unchanged.',
	startBlank: 'Start blank',
	useTemplate: (label: string) => `Use ${label}`,
	startingNote: 'A starting point replaces only this unsaved draft.',
	programName: 'Program name',
	description: 'Description',
	days: 'Days',
	dayName: (n: number) => `Day ${n} name`,
	openDay: (name: string) => `Open ${name}`,
	untitledDay: (n: number) => `Day ${n}`,
	exerciseCount: (n: number) => `${n} ${n === 1 ? 'exercise' : 'exercises'}`,
	addDay: 'Add day',
	moveUp: (what: string) => `Move ${what} up`,
	moveDown: (what: string) => `Move ${what} down`,
	remove: (what: string) => `Remove ${what}`,
	review: 'Review program',
	backToProgram: '← Program',
	backToDay: (name: string) => `← ${name}`,
	dayNotes: 'Day notes',
	alternatesWith: 'Alternates with',
	alternatesNote: 'Pick one of these on a turn, not both.',
	noAlternate: 'None',
	exercises: 'Exercises',
	addExercise: 'Add exercise',
	openExercise: (name: string) => `Edit ${name}`,
	chooseExercise: 'Choose an exercise',
	changeExercise: 'Change exercise',
	sets: 'Sets',
	repRange: 'Rep range',
	repsMin: 'Fewest reps',
	repsMax: 'Most reps',
	rir: 'Reps in reserve',
	rest: 'Rest',
	restShort: 'Short (90–120 s)',
	restLong: 'Long (2–3 min)',
	less: (what: string) => `Fewer ${what}`,
	more: (what: string) => `More ${what}`,
	customize: 'Customize sets',
	usePattern: 'Back to equal sets',
	customNote:
		'These sets differ (warm-ups, a top set with backoffs, timed sets, loads or notes), so each is edited on its own.',
	advanced: 'Advanced',
	tier: 'Tier',
	tiers: {
		main: 'Main — top set + backoffs',
		secondary: 'Secondary — straight sets',
		isolation: 'Isolation — straight sets'
	},
	policy: 'Progression',
	policies: {
		standard: 'Standard',
		cautious: 'Cautious — you advance it',
		hold: 'Hold — no progression'
	},
	exerciseNotes: 'Exercise notes',
	set: (n: number) => `Set ${n}`,
	role: 'Type',
	roles: { warmup: 'Warm-up', top: 'Top', backoff: 'Backoff', working: 'Working' },
	metric: 'Target',
	metrics: { reps: 'Reps', seconds: 'Seconds' },
	targetMin: 'Minimum',
	targetMax: 'Maximum',
	restMin: 'Rest from (s)',
	restMax: 'Rest to (s)',
	initialLoad: 'Starting load',
	setNotes: 'Set notes',
	addSet: 'Add set',
	problems: (n: number) => `${n} ${n === 1 ? 'problem' : 'problems'}`,
	fixFirst: 'Fix the marked items, then review again.',
	// The picker.
	pickerTitle: 'Choose an exercise',
	search: 'Search exercises',
	create: (name: string) => `Create “${name}”`,
	newInDraft: 'New in this program',
	library: 'Your exercises',
	equipment: 'Equipment',
	lowerBody: 'Lower body (moves up in bigger steps)',
	use: 'Use this exercise',
	close: 'Close',
	equipmentLabels: {
		barbell: 'Barbell',
		'barbell-ez': 'EZ bar',
		dumbbell: 'Dumbbell',
		bodyweight: 'Bodyweight',
		band: 'Band',
		'machine-plate': 'Plate-loaded machine',
		'machine-stack': 'Stack machine',
		cable: 'Cable',
		smith: 'Smith machine'
	} as Record<string, string>,
	// Review.
	backToEditing: 'Back to editing',
	save: 'Save program',
	saveVersion: 'Save as new version',
	saving: 'Saving…'
} as const;
