-- 0009 ownership: per-user scoping.
--
-- GENERATED BY drizzle-kit, with one deliberate exception: the
-- `workout_log_imports` unique-constraint drop is moved from position 1 to
-- the end of the file. drizzle-kit emitted it first because the TS schema no
-- longer declares the global unique; it reads more clearly next to the
-- compound unique that replaces it. Everything else is emitted verbatim — no
-- DDL in this file is hand-written.
--
-- Columns are added NULLABLE and the NOT NULL alters are deliberately
-- DEFERRED to a follow-up migration (T3), because the application code that
-- populates user_id does not exist yet. Applying NOT NULL now would fail:
-- every existing row is NULL, and the sentinel insert + backfill that would
-- fill them belong in the migration written alongside the code that owns the
-- new column. See the T1b handoff for the decision this needs.
--
-- owner_user_id on equipment_models is nullable PERMANENTLY — NULL means
-- "global equipment catalogue entry". It is reference data, not user data,
-- so existing rows are intentionally left un-owned.
--
-- All nine FKs are ON DELETE NO ACTION, not CASCADE. Deleting an account
-- must never silently delete workout history.

ALTER TABLE "equipment_models" ADD COLUMN "owner_user_id" text;--> statement-breakpoint
ALTER TABLE "exercises" ADD COLUMN "user_id" text;--> statement-breakpoint
ALTER TABLE "gyms" ADD COLUMN "user_id" text;--> statement-breakpoint
ALTER TABLE "pain_events" ADD COLUMN "user_id" text;--> statement-breakpoint
ALTER TABLE "program_draft_requests" ADD COLUMN "user_id" text;--> statement-breakpoint
ALTER TABLE "programs" ADD COLUMN "user_id" text;--> statement-breakpoint
ALTER TABLE "sessions" ADD COLUMN "user_id" text;--> statement-breakpoint
ALTER TABLE "sets" ADD COLUMN "user_id" text;--> statement-breakpoint
ALTER TABLE "workout_log_imports" ADD COLUMN "user_id" text;--> statement-breakpoint
ALTER TABLE "equipment_models" ADD CONSTRAINT "equipment_models_owner_user_id_user_id_fk" FOREIGN KEY ("owner_user_id") REFERENCES "auth"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "exercises" ADD CONSTRAINT "exercises_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "gyms" ADD CONSTRAINT "gyms_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pain_events" ADD CONSTRAINT "pain_events_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "program_draft_requests" ADD CONSTRAINT "program_draft_requests_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "programs" ADD CONSTRAINT "programs_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sets" ADD CONSTRAINT "sets_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "workout_log_imports" ADD CONSTRAINT "workout_log_imports_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "equipment_models_owner_user_id_idx" ON "equipment_models" USING btree ("owner_user_id");--> statement-breakpoint
CREATE INDEX "exercises_user_id_idx" ON "exercises" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "gyms_user_id_idx" ON "gyms" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "program_draft_requests_user_id_idx" ON "program_draft_requests" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "programs_user_id_idx" ON "programs" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "workout_log_imports_user_id_idx" ON "workout_log_imports" USING btree ("user_id");--> statement-breakpoint
ALTER TABLE "exercises" ADD CONSTRAINT "exercises_user_id_name_unique" UNIQUE("user_id","name");--> statement-breakpoint
-- Drop the GLOBAL source_sha256 unique, replaced by the per-owner one added
-- above. Two users importing the same file must both be allowed; re-importing
-- your own is still blocked.
--
-- BOTH NAMES ARE DROPPED, and this is not belt-and-braces. Migration 0007
-- declared the column as inline `"source_sha256" text NOT NULL UNIQUE`, so
-- Postgres auto-named the constraint `workout_log_imports_source_sha256_key`.
-- The 0007 Drizzle snapshot records it as `..._unique` instead — the snapshot
-- invents a name Postgres never used. Drizzle therefore generated a DROP for
-- a constraint that does not exist, which fails outright.
--
-- Verified against production and the test DB: both have the `_key` name.
-- The `_unique` form is kept so this migration also works on any database
-- where the constraint was created from the snapshot rather than from 0007.
--
-- If BOTH drops are no-ops the global unique is already gone, which is the
-- desired end state either way. There is no case where skipping the drop
-- leaves a global unique behind silently, because the names Postgres could
-- have given it are covered.
ALTER TABLE "workout_log_imports" DROP CONSTRAINT IF EXISTS "workout_log_imports_source_sha256_key";--> statement-breakpoint
ALTER TABLE "workout_log_imports" DROP CONSTRAINT IF EXISTS "workout_log_imports_source_sha256_unique";
