-- 0009 ownership: per-user scoping. Additive and fully reversible.
--
-- GENERATED BY drizzle-kit, with three hand edits, all noted inline below:
--   1. the workout_log_imports unique drop is moved from position 1 to the
--      end of the file;
--   2. that drop is duplicated under a second name, with IF EXISTS on both;
--   3. the header you are reading.
-- Nothing else is hand-written.
--
-- Columns are added NULLABLE. The NOT NULL alters, the sentinel insert and
-- the backfill are DEFERRED to 0010_ownership_not_null, which is the last
-- commit of T3. Reason: notNull() in the TS schema makes userId required in
-- $inferInsert, and no code populates it until T3 threads the owner through
-- the call sites. Applying NOT NULL here would fail on a populated database,
-- since every existing row is NULL.
--
-- 0010 is the irreversible step, and it must not be applied before the T3
-- code that writes and filters user_id is deployed alongside it. T3 code
-- against an un-backfilled database would filter every scoped query to zero
-- rows and the app would look empty.
--
-- The global UNIQUE(exercises.name) is deliberately KEPT in this migration
-- and dropped in 0010 instead. Reason: program-builder.ts quick-add still
-- does onConflictDoNothing({ target: exercises.name }), which throws at
-- runtime unless the global unique exists. T3 rewrites that call site; until
-- then, dropping it here would break quick-add.
--
-- equipment_models.owner_user_id is nullable PERMANENTLY, not deferred. NULL
-- means "global equipment catalogue entry" — reference data, not user data,
-- so existing rows stay shared rather than being backfilled to a sentinel.
--
-- All nine FKs are ON DELETE NO ACTION, not CASCADE. Deleting an account must
-- never silently delete workout history. Contrast Better Auth's own auth.*
-- FKs, which cascade — correct there, wrong here.
--
-- The nine user_id columns are text, not uuid. Better Auth generates user.id
-- itself as a 32-char alphanumeric string, so every FK to auth.user is text.
-- See the note on programs.userId in schema.ts.

ALTER TABLE "equipment_models" ADD COLUMN "owner_user_id" text;--> statement-breakpoint
ALTER TABLE "exercises" ADD COLUMN "user_id" text;--> statement-breakpoint
ALTER TABLE "gyms" ADD COLUMN "user_id" text;--> statement-breakpoint
ALTER TABLE "pain_events" ADD COLUMN "user_id" text;--> statement-breakpoint
ALTER TABLE "program_draft_requests" ADD COLUMN "user_id" text;--> statement-breakpoint
ALTER TABLE "programs" ADD COLUMN "user_id" text;--> statement-breakpoint
ALTER TABLE "sessions" ADD COLUMN "user_id" text;--> statement-breakpoint
ALTER TABLE "sets" ADD COLUMN "user_id" text;--> statement-breakpoint
ALTER TABLE "workout_log_imports" ADD COLUMN "user_id" text;--> statement-breakpoint
ALTER TABLE "equipment_models" ADD CONSTRAINT "equipment_models_owner_user_id_user_id_fk" FOREIGN KEY ("owner_user_id") REFERENCES "auth"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "exercises" ADD CONSTRAINT "exercises_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "gyms" ADD CONSTRAINT "gyms_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pain_events" ADD CONSTRAINT "pain_events_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "program_draft_requests" ADD CONSTRAINT "program_draft_requests_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "programs" ADD CONSTRAINT "programs_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sets" ADD CONSTRAINT "sets_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "workout_log_imports" ADD CONSTRAINT "workout_log_imports_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "equipment_models_owner_user_id_idx" ON "equipment_models" USING btree ("owner_user_id");--> statement-breakpoint
CREATE INDEX "exercises_user_id_idx" ON "exercises" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "gyms_user_id_idx" ON "gyms" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "pain_events_user_id_idx" ON "pain_events" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "program_draft_requests_user_id_idx" ON "program_draft_requests" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "programs_user_id_idx" ON "programs" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "sessions_user_id_idx" ON "sessions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "sets_user_id_idx" ON "sets" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "workout_log_imports_user_id_idx" ON "workout_log_imports" USING btree ("user_id");--> statement-breakpoint
ALTER TABLE "exercises" ADD CONSTRAINT "exercises_user_id_name_unique" UNIQUE("user_id","name");--> statement-breakpoint
ALTER TABLE "workout_log_imports" ADD CONSTRAINT "workout_log_imports_user_sha256_unique" UNIQUE("user_id","source_sha256");--> statement-breakpoint
-- Hand edit 1 + 2: drop the GLOBAL source_sha256 unique, replaced by the
-- per-owner unique added immediately above. Two users importing the same
-- file must both be allowed; re-importing your own is still blocked.
--
-- BOTH NAMES ARE DROPPED. Migration 0007 declared the column as inline
-- "source_sha256" text NOT NULL UNIQUE, so Postgres auto-named the
-- constraint workout_log_imports_source_sha256_key, while the 0007 Drizzle
-- snapshot records it as ..._unique — a name Postgres never used. The
-- generator emitted only the phantom drop, which fails outright:
--   ERROR: constraint "workout_log_imports_source_sha256_unique" ... does not exist
-- Verified against production: the real name is _key.
--
-- exercises_name_unique is NOT dropped here — see the header.
ALTER TABLE "workout_log_imports" DROP CONSTRAINT IF EXISTS "workout_log_imports_source_sha256_key";--> statement-breakpoint
ALTER TABLE "workout_log_imports" DROP CONSTRAINT IF EXISTS "workout_log_imports_source_sha256_unique";
